/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicalDemo;

/**
 *
 * @author My Pc
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        ajTextField1 = new javax.swing.JTextField();
        threejButton1 = new javax.swing.JButton();
        twojButton2 = new javax.swing.JButton();
        onejButton4 = new javax.swing.JButton();
        sevenjButton6 = new javax.swing.JButton();
        fivejButton7 = new javax.swing.JButton();
        sixjButton8 = new javax.swing.JButton();
        errjButtone9 = new javax.swing.JButton();
        ninejButton10 = new javax.swing.JButton();
        fourjButton11 = new javax.swing.JButton();
        eightjButton14 = new javax.swing.JButton();
        dotjButton17 = new javax.swing.JButton();
        zerojButton18 = new javax.swing.JButton();
        starjButton20 = new javax.swing.JButton();
        subjButton21 = new javax.swing.JButton();
        addjButton22 = new javax.swing.JButton();
        dividejButton23 = new javax.swing.JButton();
        addjButton23 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clac");
        setAlwaysOnTop(true);
        setResizable(false);

        threejButton1.setText("3");
        threejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threejButton1ActionPerformed(evt);
            }
        });

        twojButton2.setText("2");
        twojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twojButton2ActionPerformed(evt);
            }
        });

        onejButton4.setText("1");
        onejButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onejButton4ActionPerformed(evt);
            }
        });

        sevenjButton6.setText("7");
        sevenjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenjButton6ActionPerformed(evt);
            }
        });

        fivejButton7.setText("5");
        fivejButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivejButton7ActionPerformed(evt);
            }
        });

        sixjButton8.setText("6");
        sixjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixjButton8ActionPerformed(evt);
            }
        });

        errjButtone9.setText("=");
        errjButtone9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errjButtone9ActionPerformed(evt);
            }
        });

        ninejButton10.setText("9");
        ninejButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninejButton10ActionPerformed(evt);
            }
        });

        fourjButton11.setText("4");
        fourjButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourjButton11ActionPerformed(evt);
            }
        });

        eightjButton14.setText("8");
        eightjButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightjButton14ActionPerformed(evt);
            }
        });

        dotjButton17.setText(".");
        dotjButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotjButton17ActionPerformed(evt);
            }
        });

        zerojButton18.setText("0");
        zerojButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerojButton18ActionPerformed(evt);
            }
        });

        starjButton20.setText("*");
        starjButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starjButton20ActionPerformed(evt);
            }
        });

        subjButton21.setText("-");
        subjButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjButton21ActionPerformed(evt);
            }
        });

        addjButton22.setText("+");
        addjButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton22ActionPerformed(evt);
            }
        });

        dividejButton23.setText("/");
        dividejButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividejButton23ActionPerformed(evt);
            }
        });

        addjButton23.setText("c");
        addjButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton23ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("ON");

        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajTextField1)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(onejButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(twojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fourjButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fivejButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sixjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(subjButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(threejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dividejButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dotjButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zerojButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(errjButtone9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(starjButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sevenjButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(eightjButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton2))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addjButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ninejButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addjButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(ajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addComponent(addjButton23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addjButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sevenjButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightjButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninejButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourjButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fivejButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dividejButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onejButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotjButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zerojButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errjButtone9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(starjButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sevenjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenjButton6ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"7");
    }//GEN-LAST:event_sevenjButton6ActionPerformed

    private void onejButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onejButton4ActionPerformed
        // TODO add your handling code here:
       ajTextField1.setText(ajTextField1.getText()+"1");
        
    }//GEN-LAST:event_onejButton4ActionPerformed

    private void twojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twojButton2ActionPerformed
        // TODO add your handling code here:
       ajTextField1.setText(ajTextField1.getText()+"2");
    }//GEN-LAST:event_twojButton2ActionPerformed

    private void threejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threejButton1ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"3");
    }//GEN-LAST:event_threejButton1ActionPerformed

    private void fourjButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourjButton11ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"4");
    }//GEN-LAST:event_fourjButton11ActionPerformed

    private void fivejButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivejButton7ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"5");
    }//GEN-LAST:event_fivejButton7ActionPerformed

    private void sixjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixjButton8ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"6");
    }//GEN-LAST:event_sixjButton8ActionPerformed

    private void eightjButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightjButton14ActionPerformed
        // TODO add your handling code here:\
        ajTextField1.setText(ajTextField1.getText()+"8");
    }//GEN-LAST:event_eightjButton14ActionPerformed

    private void ninejButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninejButton10ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"9");
    }//GEN-LAST:event_ninejButton10ActionPerformed

    private void zerojButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerojButton18ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"0");
    }//GEN-LAST:event_zerojButton18ActionPerformed

    private void addjButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton22ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"+");
    }//GEN-LAST:event_addjButton22ActionPerformed

    private void subjButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjButton21ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"-");
    }//GEN-LAST:event_subjButton21ActionPerformed

    private void dividejButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividejButton23ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"/");
    }//GEN-LAST:event_dividejButton23ActionPerformed

    private void starjButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starjButton20ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+"*");
    }//GEN-LAST:event_starjButton20ActionPerformed

    private void dotjButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotjButton17ActionPerformed
        // TODO add your handling code here:
        ajTextField1.setText(ajTextField1.getText()+".");
    }//GEN-LAST:event_dotjButton17ActionPerformed

    private void errjButtone9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errjButtone9ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_errjButtone9ActionPerformed

    private void addjButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addjButton23ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton22;
    private javax.swing.JButton addjButton23;
    private javax.swing.JTextField ajTextField1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dividejButton23;
    private javax.swing.JButton dotjButton17;
    private javax.swing.JButton eightjButton14;
    private javax.swing.JButton errjButtone9;
    private javax.swing.JButton fivejButton7;
    private javax.swing.JButton fourjButton11;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton ninejButton10;
    private javax.swing.JButton onejButton4;
    private javax.swing.JButton sevenjButton6;
    private javax.swing.JButton sixjButton8;
    private javax.swing.JButton starjButton20;
    private javax.swing.JButton subjButton21;
    private javax.swing.JButton threejButton1;
    private javax.swing.JButton twojButton2;
    private javax.swing.JButton zerojButton18;
    // End of variables declaration//GEN-END:variables
}
